[package]
name = "strcan"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
stream-cancel = "0.8.2"
tokio = { version = "1.39.2", features = ["macros", "net", "rt-multi-thread"] }
tokio-stream = { version = "0.1.15", features = ["net"] }
